apiVersion: v1
kind: Service
metadata:
  name: sela-app-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: sela-app