apiVersion: apps/v1
kind: Deployment
metadata:
        name: sela-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sela-app
  template:
    metadata:
      labels:
        app: sela-app
    spec:
      containers:
      - image: 034035432908.dkr.ecr.us-east-1.amazonaws.com/sela-test-repository:1.0
        imagePullPolicy: Always
        name: sela-test-repository


              

